# Generated by Django 3.1.4 on 2020-12-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201226_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='products',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
