# Generated by Django 3.1.4 on 2020-12-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201226_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='sell_price',
        ),
    ]
