# Generated by Django 3.1.4 on 2020-12-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
